FROM node:20

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN chmod +x /app/docker-entrypoint.dev.sh

EXPOSE 4200

ENTRYPOINT ["/app/docker-entrypoint.dev.sh"]
CMD ["npm", "start", "--", "--host", "0.0.0.0", "--port", "4200", "--poll", "2000"]

