services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - ./mongo-data:/data/db
    networks:
      - backend-network

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: express_api
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - PORT=5005
      - MONGO_URL=mongodb://admin:password123@mongodb:27017/devops_opdrachten?authSource=admin
      - DB_NAME=devops_opdrachten
    ports:
      - "5005:5005"
    depends_on:
      - mongodb
    networks:
      - backend-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    networks:
      - backend-network

  mongodb-exporter:
    image: percona/mongodb_exporter:0.40.0
    command:
      - --mongodb.uri=mongodb://admin:password123@mongodb:27017/admin
      - --collect-all
      - --compatible-mode
    depends_on:
      - mongodb
    networks:
      - backend-network

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    networks:
      - backend-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: angular_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - API_BASE_URL=http://localhost:5005
    ports:
      - "4200:4200"
    depends_on:
      - api
    networks:
      - backend-network

volumes:
    prometheus_data:

networks:
  backend-network:
    driver: bridge